#num1= int(input("please enter your number:"))
#num2= int(input("please enter your number:"))
#print( num1 + num2 )
#print(num1 * num2)
#print(num1/num2)

name=str(input())
surname=str(input())
age = str(input())
print(name,surname,age)